<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $titles = array(
            array('name'=>'Afghanistan','nationality'=>'Afghan'),
            array('name'=>'Albania','nationality'=>'Albanian'),
            array('name'=>'Algeria','nationality'=>'Algerian'),
            array('name'=>'Argentina','nationality'=>'Argentine'),
            array('name'=>'Argentina','nationality'=>'Argentinian'),
            array('name'=>'Australia','nationality'=>'Australian'),
            array('name'=>'Austria','nationality'=>'Austrian'),
            array('name'=>'Bangladesh','nationality'=>'Bangladeshi'),
            array('name'=>'Belgium','nationality'=>'Belgian'),
            array('name'=>'Bolivia','nationality'=>'Bolivian'),
            array('name'=>'Botswana','nationality'=>'Batswana'),
            array('name'=>'Brazil','nationality'=>'Brazilian'),
            array('name'=>'Bulgaria','nationality'=>'Bulgarian'),
            array('name'=>'Cambodia','nationality'=>'Cambodian'),
            array('name'=>'Cameroon','nationality'=>'Cameroonian'),
            array('name'=>'Canada','nationality'=>'Canadian'),
            array('name'=>'Chile','nationality'=>'Chilean'),
            array('name'=>'China','nationality'=>'Chinese'),
            array('name'=>'Colombia','nationality'=>'Colombian'),
            array('name'=>'Costa Rica','nationality'=>'Costa Rican'),
            array('name'=>'Croatia','nationality'=>'Croatian'),
            array('name'=>'Cuba','nationality'=>'Cuban'),
            array('name'=>'Czech Republic','nationality'=>'Czech'),
            array('name'=>'Denmark','nationality'=>'Danish'),
            array('name'=>'Dominican Republic','nationality'=>'Dominican'),
            array('name'=>'Ecuador','nationality'=>'Ecuadorian'),
            array('name'=>'Egypt','nationality'=>'Egyptian'),
            array('name'=>'El Salvador','nationality'=>'Salvadorian'),
            array('name'=>'England','nationality'=>'English'),
            array('name'=>'Estonia','nationality'=>'Estonian'),
            array('name'=>'Ethiopia','nationality'=>'Ethiopian'),
            array('name'=>'Fiji','nationality'=>'Fijian'),
            array('name'=>'Finland','nationality'=>'Finnish'),
            array('name'=>'France','nationality'=>'French'),
            array('name'=>'Germany','nationality'=>'German'),
            array('name'=>'Ghana','nationality'=>'Ghanaian'),
            array('name'=>'Greece','nationality'=>'Greek'),
            array('name'=>'Guatemala','nationality'=>'Guatemalan'),
            array('name'=>'Haiti','nationality'=>'Haitian'),
            array('name'=>'Honduras','nationality'=>'Honduran'),
            array('name'=>'Hungary','nationality'=>'Hungarian'),
            array('name'=>'Iceland','nationality'=>'Icelandic'),
            array('name'=>'India','nationality'=>'Indian'),
            array('name'=>'Indonesia','nationality'=>'Indonesian'),
            array('name'=>'Iran','nationality'=>'Iranian'),
            array('name'=>'Iraq','nationality'=>'Iraqi'),
            array('name'=>'Ireland','nationality'=>'Irish'),
            array('name'=>'Israel','nationality'=>'Israeli'),
            array('name'=>'Italy','nationality'=>'Italian'),
            array('name'=>'Jamaica','nationality'=>'Jamaican'),
            array('name'=>'Japan','nationality'=>'Japanese'),
            array('name'=>'Jordan','nationality'=>'Jordanian'),
            array('name'=>'Kenya','nationality'=>'Kenyan'),
            array('name'=>'Kuwait','nationality'=>'Kuwaiti'),
            array('name'=>'Laos','nationality'=>'Lao'),
            array('name'=>'Latvia','nationality'=>'Latvian'),
            array('name'=>'Lebanon','nationality'=>'Lebanese'),
            array('name'=>'Libya','nationality'=>'Libyan'),
            array('name'=>'Lithuania','nationality'=>'Lithuanian'),
            array('name'=>'Madagascar','nationality'=>'Malagasy'),
            array('name'=>'Malaysia','nationality'=>'Malaysian'),
            array('name'=>'Mali','nationality'=>'Malian'),
            array('name'=>'Malta','nationality'=>'Maltese'),
            array('name'=>'Mexico','nationality'=>'Mexican'),
            array('name'=>'Mongolia','nationality'=>'Mongolian'),
            array('name'=>'Morocco','nationality'=>'Moroccan'),
            array('name'=>'Mozambique','nationality'=>'Mozambican'),
            array('name'=>'Namibia','nationality'=>'Namibian'),
            array('name'=>'Nepal','nationality'=>'Nepalese'),
            array('name'=>'Netherlands','nationality'=>'Dutch'),
            array('name'=>'New Zealand','nationality'=>'New Zealand'),
            array('name'=>'Nicaragua','nationality'=>'Nicaraguan'),
            array('name'=>'Nigeria','nationality'=>'Nigerian'),
            array('name'=>'Norway','nationality'=>'Norwegian'),
            array('name'=>'Pakistan','nationality'=>'Pakistani'),
            array('name'=>'Panama','nationality'=>'Panamanian'),
            array('name'=>'Paraguay','nationality'=>'Paraguayan'),
            array('name'=>'Peru','nationality'=>'Peruvian'),
            array('name'=>'Philippines','nationality'=>'Philippine'),
            array('name'=>'Poland','nationality'=>'Polish'),
            array('name'=>'Portugal','nationality'=>'Portuguese'),
            array('name'=>'Romania','nationality'=>'Romanian'),
            array('name'=>'Russia','nationality'=>'Russian'),
            array('name'=>'Saudi Arabia','nationality'=>'Saudi'),
            array('name'=>'Scotland','nationality'=>'Scottish'),
            array('name'=>'Senegal','nationality'=>'Senegalese'),
            array('name'=>'Serbia','nationality'=>'Serbian'),
            array('name'=>'Singapore','nationality'=>'Singaporean'),
            array('name'=>'Slovakia','nationality'=>'Slovak'),
            array('name'=>'South Africa','nationality'=>'South African'),
            array('name'=>'South Korea','nationality'=>'Korean'),
            array('name'=>'Spain','nationality'=>'Spanish'),
            array('name'=>'Sri Lanka','nationality'=>'Sri Lankan'),
            array('name'=>'Sudan','nationality'=>'Sudanese'),
            array('name'=>'Sweden','nationality'=>'Swedish'),
            array('name'=>'Switzerland','nationality'=>'Swiss'),
            array('name'=>'Syria','nationality'=>'Syrian'),
            array('name'=>'Taiwan','nationality'=>'Taiwanese'),
            array('name'=>'Tajikistan','nationality'=>'Tajikistani'),
            array('name'=>'Thailand','nationality'=>'Thai'),
            array('name'=>'Tonga','nationality'=>'Tongan'),
            array('name'=>'Tunisia','nationality'=>'Tunisian'),
            array('name'=>'Turkey','nationality'=>'Turkish'),
            array('name'=>'Ukraine','nationality'=>'Ukrainian'),
            array('name'=>'United Arab Emirates','nationality'=>'Emirati'),
            array('name'=>'(The) United Kingdom','nationality'=>'British'),
            array('name'=>'(The) United States','nationality'=>'American'),
            array('name'=>'Uruguay','nationality'=>'Uruguayan'),
            array('name'=>'Venezuela','nationality'=>'Venezuelan'),
            array('name'=>'Vietnam','nationality'=>'Vietnamese'),
            array('name'=>'Wales','nationality'=>'Welsh'),
            array('name'=>'Zambia','nationality'=>'Zambian'),
            array('name'=>'Zimbabwe','nationality'=>'Zimbabwean')
        );

        foreach ($titles as $key => $value) {
            Country::create(['name' => $value['name']]);
        }
        
    }
}
